### ISSUE TITLE
Problems when upgrading to latest version (3.3.1)

### ISSUE THREAD

**Issue by gtsak1** [Notificare/notificare-sdk-android#42]
I upgraded notificare version to 3.3.1 and made the corresponding changes in code. I use Android Gradle Plugin version 7.2.2 and Gradle version 7.3.3. Also, compileSdkVersion and targetSdkVersion 31, minSdkVersion 23. 

The thing is that when tested in api 28 & 29, devices were registered to notificare, I added tags successfully and sent message successfully through dashboard. But, notification was never received. On all other apis I tested, I got this error:

_Unable to get provider re.notifica.NotificareConfigurationProvider: java.lang.IllegalStateException: No platform dependencies have been detected. Please include one of the platform-specific packages._

I have followed everything that is described in the docs regarding implementation, device registration, tags and remote notifications. I know my questions may seem quite general, so what do you need from me (logs etc) in order to help me?

I have used Notificare successfully before, till 2.7.4 version. But with Android Gradle Plugin version 3.5.4 and Gradle version 6.8, compileSdkVersion and targetSdkVersion 28. When I tried to upgrade gradle or sdkVersion, Notificare version 2.7.4 had the same problems (the aforementioned) I face now with version 3.3.1.

**Comment by hpinhal** [comment]
Hi @gtsak1 ,

Based on that exception, it seems you are missing the dependency that enables the push capabilities for your given platform.

The base `notificare-push` dependency enables the push functionality you, as a developer, will use. However, since there are two different push providers — GMS (Google Mobile Services) and HMS (Huawei Mobile Services) — we created two peer dependencies — `notificare-push-gms` and `notificare-push-hms` — allowing you to cherry-pick which platforms you want to support.

Once you include those, device registration should integrate with your phone's push provider, allowing you to receive remote notifications.

**Comment by gtsak1** [comment]
I have used these dependencies:

def notificare_version = '3.3.1'
implementation "re.notifica:notificare:$notificare_version"

implementation "re.notifica:notificare-push:$notificare_version"
implementation "re.notifica:notificare-push-gms:$notificare_version"

implementation "re.notifica:notificare-push-ui:$notificare_version"
implementation "re.notifica:notificare-push-ui-gms:$notificare_version"

I thing I am not missing something. I am not testing on huawei at the moment, so I did not include hms

**Comment by hpinhal** [comment]
We can't reproduce what you're describing.
Can you send us a small sample app that illustrates this problem?

**Comment by gtsak1** [comment]
Hi.

I created small sample apps with notificare v.3 and everything worked successfully.

Nevertheless, I did not yet manage to integrate notificare v.3 in the project I am working on, most likely due to conflicts with some other libraries we use. So, I switched back to working version 2.7.0.

I close this issue for now

**Comment by gtsak1** [comment]
Hi @hpinhal.

I have managed to integrate successfully notificare v.3 in the project I am working on. Everything works fine when testing on real devices. The only problem that remains is when running the app on some emulators in android studio (not all).

The error is:

Unable to get provider re.notifica.NotificareConfigurationProvider: java.lang.IllegalStateException: No platform dependencies have been detected. Please include one of the platform-specific packages.

Can you reproduce that (for android studio emulators only) or do you want me to send you a sample app? Where should I send it?

**Comment by hpinhal** [comment]
Hi @gtsak1,

I'm glad you were able to transition to v3.x!

I've tried testing with two different emulators but still couldn't reproduce.
- Pixel 4 API 31 w/ Play Store
- Pixel 6 Pro API 31 without Play Store

It would help if you could provide a sample and the exact settings of your emulator. You can upload a zip file in a comment through this channel.

**Comment by hpinhal** [comment]
We did some more digging and believe we found the problem you're experiencing.

I've created two emulators with the same API level but different images, as described in the image below.

![image](https://user-images.githubusercontent.com/2880250/191248197-2c0b2fd4-447b-47fe-af56-b17a2ba49bb1.png)

The first image (without the Google APIs) will experience the exception you described due to the lack of Google APIs. The second image, however, works just fine.

When you select an image for the emulator, you should have a warning (in red) for images without Google APIs.

![image](https://user-images.githubusercontent.com/2880250/191248805-9ab29e1c-5c36-4b0e-9e3d-9d2cf69027a3.png)

Make sure you select the most appropriate image — architecture and including Google APIs.

![image](https://user-images.githubusercontent.com/2880250/191248946-32898103-85b9-4b19-bd7b-4212ff19bfaa.png)


Can you confirm this was your case and that selecting an image with Google APIs works for you?

**Comment by gtsak1** [comment]
Yes, that was the problem, thank you! I am ok with this now, but is there a way for all emulators to work with v.3? I ask, because I did not face the same problem with v.2.

In the below image, Nexus 4 Api 30 2 is the working emulator for this case:
![emulators](https://user-images.githubusercontent.com/58042128/191267759-07695e2f-2e16-41a6-85db-330cdb40e046.png)

**Comment by hpinhal** [comment]
I cannot run x86_64 or x86 images on my Apple Silicon MacBook.
The architecture type you're using will differ based on your physical CPU.

However, the key part of my previous comment was regarding the availability of the Google APIs.
If you were using images without the Google APIs with v2, certain features, like remote notifications, couldn't have worked properly. In v3 we split GMS and HMS dependencies from the base feature module and enforced strict availability checks which triggered the exception you reported.

**Comment by gtsak1** [comment]
Ok, thanks
