### ISSUE TITLE
Notification deep link doesn't work on subsequent tries

### ISSUE THREAD

**Issue by DonnyRozendal** [Notificare/notificare-sdk-android#56]
It seems that intent filters aren't triggered whenever the app has previously been opened by a deep link from a cold boot. I'll explain the two scenarios.

Scenario 1:
- App has been killed
- App is opened by a notification and the deep link is triggered correctly
- User puts the app into the background
- App is opened by a notification and deep link is NOT triggered

Scenario 2:
- App has been killed
- App is opened regularly by tapping the app icon
- User puts the app into the background
- App is opened by a notification and the deep link is triggered correctly
- User puts the app into the background
- App is opened again by a notification and the deep link is triggered correctly. This can be done indefinitely and it keeps working

It seems that the second notification click on scenario 1 doesn't trigger the intents that are expected. I checked this in `onNewIntent()`. The app is simply resumed from the background and no intents are triggered. However, this is the case for scenario 2.

Is there a manifest setting that I'm missing or something?

Setup in Manifest:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    
    <data
        android:host="{host}"
        android:pathPrefix="{pathPrefix}"
        android:scheme="https" />
</intent-filter>
<intent-filter>
    <action android:name="re.notifica.intent.action.RemoteMessageOpened" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
<intent-filter>
    <action android:name="re.notifica.intent.action.NotificationOpened" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
Setup in Activity:
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    // Other code
    if (intent != null) {
        handleIntent(intent)
    }
}

override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    if (intent != null) {
        handleIntent(intent)
    }
}

private fun handleIntent(intent: Intent) {
    if (Notificare.push().handleTrampolineIntent(intent)) return
    if (intent.action == Notificare.INTENT_ACTION_NOTIFICATION_OPENED) {
        if (SDK_INT >= TIRAMISU) {
            intent.getParcelableExtra(Notificare.INTENT_EXTRA_NOTIFICATION, NotificareNotification::class.java)
        } else {
            intent.getParcelableExtra(Notificare.INTENT_EXTRA_NOTIFICATION)
        }?.also {
            Notificare.pushUI().presentNotification(this, it)
        }
    }
}
```

**Comment by hpinhal** [comment]
Hi @DonnyRozendal,

At first glance, your code looks correct.
However, I could not reproduce what you described using the sample app in this repository.

By looking at the partial manifest you shared, it's worth mentioning that you're using Dynamic Links — not typical deep links.
HTTPS links must be verified with `android:autoVerify="true"`. The app signature must be configured in the provider you're using. If you're using Notificare Links, you can find more information [here](https://docs.notifica.re/guides/apps/services/links/).

Furthermore, from the flow you described, you should expect the following:
- User taps on notification of type Deep Link.
- Either `onCreate` or `onNewIntent` will trigger with the `RemoteMessageOpened` intent action, handled by `Notificare.push().handleTrampolineIntent()`.
- `onNewIntent` will trigger with the `NotificationOpened` intent action. You must process it with `Notificare.pushUI().presentNotification()`.
- Considering the notification type is Deep Link, it will trigger `onNewIntent` with the URI in the notification.

Note that you must configure the manifest with the values you use in the notification content. Since you use HTTPS, you must also verify the intent filters. Another thing you may want to double-check is the `launchMode` of your activity.

Can you reproduce this with our sample app if this doesn't help you solve the problem?

PS: should you need to share confidential information, please refer to the [support channel](https://notificare.zendesk.com/).

**Comment by DonnyRozendal** [comment]
Another thing that's very odd. I mentioned that `intent.data` is empty whenever I use launch mode `singleTask`. I did a print statement and it turns out that it is not empty in the Activity, but it is empty when called from a Fragment that resides inside the Activity, like this: `activity?.intent?.data`. This is not the case when I'm using launch mode `standard`, where the Fragment can read the intent data. And then there still is the issue of the Activity not being recreated

**Comment by DonnyRozendal** [comment]
Furthermore, I'm not sure on how I can run the sample app myself. I'm running into an issue where it says this:
```
Task 'wrapper' not found in project ':sample'.
```

**Comment by hpinhal** [comment]
Hi @DonnyRozendal,

Since you're using the `standard` mode, every intent that targets an activity will always create a new instance of that activity. In short, the `onNewIntent` will not be called, and you'll get an instance of that activity with the intent to be processed. This is the foundation of intents in Android. If I understand correctly, you're claiming the OS is not creating a new instance of the activity (the `onResume` remark). That being the case would be a severe flaw in Android itself.

Jumping into the second part, where you changed the `launchMode`, you should do so with care because this is a foundational aspect of how your app responds to intents.
Please refer to the Android [documentation](https://developer.android.com/guide/topics/manifest/activity-element#lmode) for more information on each launch mode.

On the principle of using a single-instance activity, as I previously explained, handling a notification will launch a series of intents that must be addressed accordingly. If you're creating an activity instance for each intent, you can understand the result — which can lead to poor UX due to all the instances on the back stack.

If you believe there is a problem with our libraries, can you please provide a sample app that illustrates the problem?


PS: to run the sample app in this repo, open the project's root on Android Studio. You'll have to configure the `notificare-services` and `google-services` with an `applicationId` you can manage.

I hope this helps.

**Comment by DonnyRozendal** [comment]
Hey @hpinhal ,

It took me a while, but I finally created a public sample project that illustrates the issue. You can clone it here: https://github.com/DonnyRozendal/notificare-test

This is a very simple template project that has a single Activity with three bottom navigation destinations. You can add your own `google-services.json` and `notificare-services.json` in the `app` folder.

I have a print statement in `onViewCreated` of `HomeFragment` that will print the intent uri of the deep link. The deep link has the following format:
```
example://app/dashboard
```
This is also specified in `AndroidManifest.xml`.

Once again the issue:
- App is killed
- App is opened by tapping the notification with the deep link
- Deep link is read correctly and the print statement prints the deep link uri
- App is not killed but put into the background
- Now on any subsequent notifications with the deep link, the app is opened but simply resumed and not restarted, so therefore the deep link can't be handled correctly. This is the issue

This issue does NOT occur whenever the app is initially opened by simply tapping the app icon. In this case, whenever the app is put into the background, the notification with the deep link keeps working indefinitely.

**Comment by hpinhal** [comment]
Hi @DonnyRozendal ,

Thanks for providing the sample app.
I can confirm the described outcome upon following the steps to reproduce.

We're investigating the reason — whether this is an SDK or an OS issue.

A short description of what's happening may help understand the problem.
When you open a notification from the notification centre, and you've followed the recommended approach, the following happens:
1. Intent `re.notifica.intent.action.RemoteMessageOpened` triggered;
2. Your main activity handles the trampoline intent;
3. Intent `re.notifica.intent.action.NotificationOpened` triggered;
4. Your main activity handles the open, and presents the notification;
5. Considering the notification we're discussing is a URLScheme, a new intent is triggered with the specified URI.
6. Your main activity processes the intent URI.

With the `standard` launch mode, the OS will create a new instance of the target activity for each triggered intent. However, on the second attempt, the OS produces an odd behaviour. As you described, the application is resumed, but a new activity is not created, nor `onNewIntent` is triggered.

Although we don't mention the launch mode in our documentation, you should be using `singleTop` or `singleTask` (recommended) based on your requirements. We're updating our documentation to reflect this. 

In most cases, you will want a single instance of the target activity on the back stack. Otherwise, the users will go back to the "same" UI when pressing the back button. This results in poor navigation UX. Hence, delivering sequential intents to the same instance of the activity.

While we don't know the specific use case for these deep links, you may want to handle them in the activity itself instead of the fragment. In case you want to pass that along to the navigation controller, you can always use [handleDeepLink](https://developer.android.com/reference/androidx/navigation/NavController#handleDeepLink(android.content.Intent)).

**Comment by DonnyRozendal** [comment]
Hey @hpinhal Did you have any new insights in the mean time whether this is an SDK or OS issue?

**Comment by hpinhal** [comment]
Hi @DonnyRozendal ,

The issue you experienced is not related to the SDK.
As I explained in my previous response, the OS resumes the application, but there is no _signal_ whatsoever about the new intent. Therefore, there's no way for us to process it correctly. 

However, I expected you to switch to the recommended approach described in my previous response and the [documentation](https://docs.notifica.re/sdk/v3/android/implementation/push/#receiving-notifications).
Although I'm unaware of the reasons for continuing to use the `standard` launch mode, even when handling deep links, I'm sure there are alternatives when using the recommended launch mode.

**Comment by DonnyRozendal** [comment]
Hey @hpinhal Ah my bad, I thought you meant that the alternative launch modes were an optional setting and would not contribute to the solution of the actual issue at all. I thought that you meant that those launch modes are only helpful for not having multiple instances of an Activity, and not necessarily adhering to my specific problem.

I tried the launch modes that you mentioned. Both `singleTop` as well as `singleTask`. Using these launch modes does not solve the issue. In fact, it makes the issue even worse because this somehow breaks the deep link functionality entirely for ALL scenarios. You can try and recreate this behavior yourself by using the sample project that I shared a while back. Maybe you can make some sense of this.

Furthermore, I have encountered another peculiar thing. I am now also using the HTML markup feature of Notificare for push notifications. And this feature actually had the exact same buggy behavior as a deep link notification, where the markup page would not be shown on subsequent notification presses whenever the initial app launch was done by a notification press as opposed to an app icon press. However, using an alternative launch mode here like `singleTop` or `singleTask` miraculously DID solve the issue here! However, this did mean that deep link notifications would stop working entirely as I mentioned before.

So as a workaround for now, I am using the `singleTop` launch mode to fix the markup notifications and I am manually reading Notificare notifications to check whether the app has been opened by a specific notification. Like this:
```
// In handleIntent of MainActivity
val notificareNotification = intent.getParcelableExtra(
    Notificare.INTENT_EXTRA_NOTIFICATION,
    NotificareNotification::class.java
)
val launchedFromSpecificDeepLink = notificareNotification.extra["type"] == "SpecificType"
```
I know that this might not be the most recommended approach because I'm relying on being able to dive into the received Notification in a specific manner which might break on SDK updates. But it is the only solution at the moment that solves all cases for me.

**Comment by hpinhal** [comment]
Hi @DonnyRozendal,

The `singleTask/singleTop` launch mode is required.
Otherwise, you'll get several instances of your launcher activity due to handling the intermediate intents.

After making some changes to the sample you provided, the deep links work just fine.

Here are what's missing in your implementation:

1. The activity needs the launch mode.
```
<activity
    android:name=".ui.MainActivity"
    android:exported="true"
    android:label="@string/app_name"
    android:launchMode="singleTask">
```

2. The `handleIntent` needs to handle the deep link intent our SDK will send due to calling `presentNotification()`.
```
    @Suppress("DEPRECATION")
    private fun handleIntent(intent: Intent) {
        if (Notificare.push().handleTrampolineIntent(intent)) return

        if (intent.action == Notificare.INTENT_ACTION_NOTIFICATION_OPENED) {
            intent.getParcelableExtra<NotificareNotification>(Notificare.INTENT_EXTRA_NOTIFICATION)?.also {
                Notificare.pushUI().presentNotification(this, it)
            }

            return
        }

        if (intent.data != null) {
            // Handle your deep link here.
            Toast.makeText(this, "uri = ${intent.data}", Toast.LENGTH_LONG).show()
        }
    }
```

Note that your `DashboardFragment.onViewCreated()` will only render the URI from the **very first** intent that opened the app. That will be `null` since the first intent will be the `RemoteMessageOpened` action.

I would suggest running your tests on the sample to make sure it works as expected.
I hope this then helps you triage the issue in your app.
