### ISSUE TITLE
Cleartext Credentials Stored in Device

### ISSUE THREAD

**Issue by gtsak1** [Notificare/notificare-sdk-android#97]
Penetration tests show that the mobile application can store sensitive information inside the device, due to Notificare's register function:

`public fun register(userId: String?, userName: String?, callback: NotificareCallback<Unit>)`

![image-2023-02-08-15-26-06-663](https://github.com/Notificare/notificare-sdk-android/assets/58042128/3bb99fcf-adab-47f3-8142-7ce27c26a019)

Is there a way to hide or encrypt the userName present in re.notifica.preferences.xml file shown in the image above?

**Comment by hpinhal** [comment]
Hi @gtsak1,

The `userName` stored there is meant for a person's name, not login credentials.
You shouldn't use `register(userId, userName)` through the SDK if you consider this a security concern.
Using device-level user registration is considered insecure since the application keys can be accessed by reverse engineering the application.

Consider moving to the recommended API-level user registration instead.
The application communicates with your backend, which ensures strong user authentication. In turn, your backend relays that information to our REST API.

You can find more information on enabling API-level user authentication [here](https://docs.notifica.re/guides/apps/configure-app/) and how to assign a user through the REST API in [this](https://api-docs.notifica.re/#tag/Device/operation/putDeviceUser) link.

The SDK won't store the user details locally when you assign a user through the REST API.

I think it's also important to mention that it's best to disclose potential vulnerabilities through private channels. The screenshot you provided contains another sensitive piece of information, although I'm sure this is from a testing application and device.
For future reference, please use our [support portal](https://notificare.zendesk.com/) to discuss sensitive topics.

**Comment by gtsak1** [comment]
Thank you for the response and suggestions.
